### ISSUE TITLE
Certain raster content not rendered

### ISSUE THREAD

**Issue by AlisterH** [JakubMelka/PDF4QT#202] opened 2024-08-10 13:33 UTC
Your software does not render ~~vector~~ graphics in some pdfs correctly.
Here is an example - for some reason this lady produces pdfs with a whole lot of ~~vectorised~~ rasterised text, none of which is rendered correctly.  In some places there is instead a gradient shown where the text should be, but in other places nothing.
https://missionbibleclass.org/wp-content/uploads/2020/01/10_4-Sermon-on-the-Mount-in-A4-size-paper.pdf

**Comment by AlisterH** [comment] 2024-08-11 18:07
Sorry, I'm mistaken, that pdf seems to have _rasterised_ text that isn't rendered correctly, not vectorised.

**Comment by JakubMelka** [comment] 2024-09-01 10:25
Hello @AlisterH, images with the soft mask were handled incorrectly. The size of the image in the attached PDF document was 2x2 pixels; however, the soft mask was much larger. I handled this case incorrectly—the soft mask was adjusted to the image size, which was 2x2 pixels in this case. The issue is now fixed, and the image is scaled to match the larger mask size.

**Closed by JakubMelka** 2024-09-01 10:25 UTC
